/********************************************
 *Copyright(C) 2021 by DefaultCompany 
 *All rights reserved. 
 *FileName:     MonoSingleTon.cs 
 *Author:       FuQiangJun 
 *Version:      1.0 
 *UnityVersionï¼š2018.3.4f1 
 *Date:         2021-02-18 09:13:28 
 *Email:        17611473176@163.com 
 *Description:    
 *History: 
*******************************************/
using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public class MonoSingleTon<T> : MonoBehaviour where T : MonoSingleTon<T>
{
    private static bool isInit;
    private static T instance;
    public static T Instance
    {
        get
        {
            if (instance == null)
            {
                GameObject go = new GameObject(typeof(T).ToString());
                go.AddComponent<T>();
            }
            return instance;
        }
    }

    protected virtual void Awake()
    {
        if (instance == null && !isInit)
        {
            isInit = true;
            instance = GetComponent<T>();
            DontDestroyOnLoad(this.gameObject);
        }
        else
        {
            Destroy(gameObject);
        }
    }
    

    protected virtual void OnDestroy()
    {
        if (instance != null) instance = null;
    }

}
